//
// Created by david on 1/18/2026.
//

#ifndef EJERCICIOSMATRICES_MATRIZTEMPERATURAS_H
#define EJERCICIOSMATRICES_MATRIZTEMPERATURAS_H


class MatrizTemperaturas {
};


#endif //EJERCICIOSMATRICES_MATRIZTEMPERATURAS_H